/* ============================================================
 * css_mappings.js — CSS Module Class Name Mappings
 * This file contains static mappings extracted from app.js.
 * ============================================================ */

const JA = "_headerRight_wxni4_1",
        PA = "_action_wxni4_7",
        kA = "_authorization_wxni4_18",
        HA = "_authorizationLeft_wxni4_22",
        jA = "_authorizationRight_wxni4_23",
        IA = "_authorizationTitle_wxni4_34",
        DA = "_titleClientname_wxni4_40",
        LA = "_titleVersion_wxni4_45",
        wA = "_authorizationForm_wxni4_55",
        _A = "_formInput_wxni4_60",
        $A = "_inputEye_wxni4_75",
        tg = "_formButtons_wxni4_86",
        eg = "_buttonsChoose_wxni4_91",
        ng = "_line_wxni4_97",
        ag = "_authorizationForgot_wxni4_108",
        lg = "_rightOverlay_wxni4_119",
        rg = "_rightOverlayText_wxni4_137",
        ig = "_text_wxni4_149",
        og = "_textTitle_wxni4_157",
        ug = "_textCenter_wxni4_170",
        sg = "_textIcon_wxni4_173",
        Vg = "_textDescription_wxni4_176",
        fg = "_textContent_wxni4_179",
        cg = "_rightOverlayButtons_wxni4_182",
        qg = "_rightOverlayButton_wxni4_182",
        dg = "_active_wxni4_198",
        Ct = {
          headerRight: JA,
          action: PA,
          authorization: kA,
          authorizationLeft: HA,
          authorizationRight: jA,
          authorizationTitle: IA,
          titleClientname: DA,
          titleVersion: LA,
          authorizationForm: wA,
          formInput: _A,
          inputEye: $A,
          formButtons: tg,
          buttonsChoose: eg,
          line: ng,
          authorizationForgot: ag,
          rightOverlay: lg,
          rightOverlayText: rg,
          text: ig,
          textTitle: og,
          textCenter: ug,
          textIcon: sg,
          textDescription: Vg,
          textContent: fg,
          rightOverlayButtons: cg,
          rightOverlayButton: qg,
          active: dg,
        };

const hg = "_inputContainer_1br4c_1",
        Fg = "_inputIcon_1br4c_5",
        yg = "_inputXMark_1br4c_14",
        AV = { inputContainer: hg, inputIcon: Fg, inputXMark: yg };

const Ag = "_outline_8816a_17",
        gg = "_fill_8816a_25",
        Xg = "_loader_8816a_34",
        Uo = { outline: Ag, fill: gg, loader: Xg };

const Mg = "_home_10but_1",
        Og = "_homeVersions_10but_1",
        Ng = "_version_10but_6",
        Jg = "_versionContent_10but_29",
        Pg = "_contentDisplay_10but_40",
        kg = "_contentGameVersion_10but_45",
        Hg = "_contentButtonStart_10but_49",
        jg = "_loading_10but_94",
        Ig = "_preloaderOverlay_10but_109",
        Dg = "_circularLoader_10but_123",
        Lg = "_bg_10but_138",
        wg = "_fill_10but_141",
        _g = "_percentage_10but_147",
        $g = "_loaderText_10but_157",
        tX = "_noAccess_10but_165",
        Ve = {
          home: Mg,
          homeVersions: Og,
          version: Ng,
          versionContent: Jg,
          contentDisplay: Pg,
          contentGameVersion: kg,
          contentButtonStart: Hg,
          loading: jg,
          preloaderOverlay: Ig,
          circularLoader: Dg,
          bg: Lg,
          fill: wg,
          percentage: _g,
          loaderText: $g,
          noAccess: tX,
        };

const oX = "_settings_fqdp4_1",
        uX = "_settingDouble_fqdp4_6",
        sX = "_setting_fqdp4_1",
        VX = "_settingRam_fqdp4_25",
        ga = { settings: oX, settingDouble: uX, setting: sX, settingRam: VX };

const cX = "_header_a9vqm_1",
        qX = "_active_a9vqm_8",
        dX = "_headerLeft_a9vqm_17",
        pX = "_headerAccount_a9vqm_22",
        KX = "_accountAvatar_a9vqm_32",
        vX = "_accountInfo_a9vqm_37",
        UX = "_infoName_a9vqm_37",
        mX = "_infoSubscribe_a9vqm_40",
        hX = "_headerNickname_a9vqm_44",
        FX = "_headerRight_a9vqm_58",
        yX = "_action_a9vqm_69",
        de = {
          header: cX,
          active: qX,
          headerLeft: dX,
          headerAccount: pX,
          accountAvatar: KX,
          accountInfo: vX,
          infoName: UX,
          infoSubscribe: mX,
          headerNickname: hX,
          headerRight: FX,
          action: yX,
        };

const XX = "_background_183py_1",
        WX = "_appContainer_183py_14",
        SX = "_containerNavigation_183py_21",
        zX = "_containerContent_183py_25",
        Wo = {
          background: XX,
          appContainer: WX,
          containerNavigation: SX,
          containerContent: zX,
        };

const CX = "_navigation_1twi2_1",
        QX = "_active_1twi2_9",
        bX = "_navigationHeader_1twi2_18",
        BX = "_headerIcon_1twi2_24",
        RX = "_path_1twi2_25",
        ZX = "_current_1twi2_41",
        xX = "_navigationFooter_1twi2_50",
        TX = "_footerIcon_1twi2_50",
        Le = {
          navigation: CX,
          active: QX,
          navigationHeader: bX,
          headerIcon: BX,
          path: RX,
          current: ZX,
          navigationFooter: xX,
          footerIcon: TX,
        };

